// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpdgmp0pIVlX6CUuFYjimwdZWKyR-pxLI',
    appId: '1:530571267662:web:15b7b46a77fad93752bd1f',
    messagingSenderId: '530571267662',
    projectId: 'pizza-app-8sc-gmao',
    authDomain: 'pizza-app-8sc-gmao.firebaseapp.com',
    storageBucket: 'pizza-app-8sc-gmao.firebasestorage.app',
    measurementId: 'G-CY0PKH1TGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrW_aaER11W1bJCkTMmkXMAl1MrY_eHE',
    appId: '1:530571267662:android:a6eaa01b25fb647f52bd1f',
    messagingSenderId: '530571267662',
    projectId: 'pizza-app-8sc-gmao',
    storageBucket: 'pizza-app-8sc-gmao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhds6ImPBLtzWOmZv1Ou7v7PvS4QrmD4',
    appId: '1:530571267662:ios:12fc5facf13f80d952bd1f',
    messagingSenderId: '530571267662',
    projectId: 'pizza-app-8sc-gmao',
    storageBucket: 'pizza-app-8sc-gmao.firebasestorage.app',
    iosBundleId: 'com.example.pizzaAppAdminGmao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAhds6ImPBLtzWOmZv1Ou7v7PvS4QrmD4',
    appId: '1:530571267662:ios:12fc5facf13f80d952bd1f',
    messagingSenderId: '530571267662',
    projectId: 'pizza-app-8sc-gmao',
    storageBucket: 'pizza-app-8sc-gmao.firebasestorage.app',
    iosBundleId: 'com.example.pizzaAppAdminGmao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpdgmp0pIVlX6CUuFYjimwdZWKyR-pxLI',
    appId: '1:530571267662:web:b96dddaa0ad1738852bd1f',
    messagingSenderId: '530571267662',
    projectId: 'pizza-app-8sc-gmao',
    authDomain: 'pizza-app-8sc-gmao.firebaseapp.com',
    storageBucket: 'pizza-app-8sc-gmao.firebasestorage.app',
    measurementId: 'G-N3NXNKHLQD',
  );
}
